### ISSUE TITLE
ChromePlugin Card ID question

### ISSUE THREAD

**Issue by krestyanikov** [tobybatch/TrelloBundle#8]
Hello @tobybatch 

I was looking for a plugin for Kimai and your plugin is amazing. I tried it with Trello and realized that there was a little problem. I expected the meta field External Card/Project ID to be filled after I picked the card and filled the time, however it turned out to be wrong. I found that another ChromePlugin Card ID meta field was installed instead. Is this behavior correct? Or should I replace ChromePlugin Card ID with External Card/Project ID in ChromeController?

Also, I don't understand how you plan to use the External Card/Project ID, because knowing the carriage ID I still can't make a quick transition to card. Perhaps it would be more useful to keep a link to the card? 

Thank you!

**Comment by tobybatch** [comment]
That was a bug, should be fixed
